apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev.api-ant.longu.dev

spec:
  secretName: dev.api-ant.longu.dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: 'dev.api-ant.longu.dev'
  dnsNames:
    - dev.api-ant.longu.dev
