apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ./certificate.yaml

patches:
  - target:
      kind: IngressRoute
      labelSelector: "role=api"
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`dev.api-ant.longu.dev`)
      - op: add
        path: /spec/tls
        value:
          secretName: dev.api-ant.longu.dev-tls

