apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  labels:
    role: database
spec:
  selector:
    matchLabels:
      role: database
  serviceName: database
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        storageClassName: managened-nfs-storage
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 3Gi
  template:
    metadata:
      labels:
        role: database
    spec:
      containers:
        - name: database
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: ant
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: root
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    role: database
spec:
  selector:
    role: database
  ports:
    - port: 5432
      targetPort: 5432


